/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as ProjectProjectidIndexImport } from './routes/project/$projectid/index'

// Create Virtual Routes

const TppLazyImport = createFileRoute('/tpp')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const TppLazyRoute = TppLazyImport.update({
  id: '/tpp',
  path: '/tpp',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/tpp.lazy').then((d) => d.Route))

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ProjectProjectidIndexRoute = ProjectProjectidIndexImport.update({
  id: '/project/$projectid/',
  path: '/project/$projectid/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/tpp': {
      id: '/tpp'
      path: '/tpp'
      fullPath: '/tpp'
      preLoaderRoute: typeof TppLazyImport
      parentRoute: typeof rootRoute
    }
    '/project/$projectid/': {
      id: '/project/$projectid/'
      path: '/project/$projectid'
      fullPath: '/project/$projectid'
      preLoaderRoute: typeof ProjectProjectidIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginRoute
  '/tpp': typeof TppLazyRoute
  '/project/$projectid': typeof ProjectProjectidIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginRoute
  '/tpp': typeof TppLazyRoute
  '/project/$projectid': typeof ProjectProjectidIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/login': typeof LoginRoute
  '/tpp': typeof TppLazyRoute
  '/project/$projectid/': typeof ProjectProjectidIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/tpp' | '/project/$projectid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/tpp' | '/project/$projectid'
  id: '__root__' | '/' | '/login' | '/tpp' | '/project/$projectid/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  LoginRoute: typeof LoginRoute
  TppLazyRoute: typeof TppLazyRoute
  ProjectProjectidIndexRoute: typeof ProjectProjectidIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  LoginRoute: LoginRoute,
  TppLazyRoute: TppLazyRoute,
  ProjectProjectidIndexRoute: ProjectProjectidIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/tpp",
        "/project/$projectid/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/tpp": {
      "filePath": "tpp.lazy.tsx"
    },
    "/project/$projectid/": {
      "filePath": "project/$projectid/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
