/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as DocsSimzConceptImport } from './routes/docs/simz-concept'
import { Route as DocsCompFuncImport } from './routes/docs/comp-func'
import { Route as DocsCodeArchImport } from './routes/docs/code-arch'
import { Route as ProjectProjectidIndexImport } from './routes/project/$projectid/index'

// Create Virtual Routes

const TppLazyImport = createFileRoute('/tpp')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const TppLazyRoute = TppLazyImport.update({
  id: '/tpp',
  path: '/tpp',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/tpp.lazy').then((d) => d.Route))

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const DocsSimzConceptRoute = DocsSimzConceptImport.update({
  id: '/docs/simz-concept',
  path: '/docs/simz-concept',
  getParentRoute: () => rootRoute,
} as any)

const DocsCompFuncRoute = DocsCompFuncImport.update({
  id: '/docs/comp-func',
  path: '/docs/comp-func',
  getParentRoute: () => rootRoute,
} as any)

const DocsCodeArchRoute = DocsCodeArchImport.update({
  id: '/docs/code-arch',
  path: '/docs/code-arch',
  getParentRoute: () => rootRoute,
} as any)

const ProjectProjectidIndexRoute = ProjectProjectidIndexImport.update({
  id: '/project/$projectid/',
  path: '/project/$projectid/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/tpp': {
      id: '/tpp'
      path: '/tpp'
      fullPath: '/tpp'
      preLoaderRoute: typeof TppLazyImport
      parentRoute: typeof rootRoute
    }
    '/docs/code-arch': {
      id: '/docs/code-arch'
      path: '/docs/code-arch'
      fullPath: '/docs/code-arch'
      preLoaderRoute: typeof DocsCodeArchImport
      parentRoute: typeof rootRoute
    }
    '/docs/comp-func': {
      id: '/docs/comp-func'
      path: '/docs/comp-func'
      fullPath: '/docs/comp-func'
      preLoaderRoute: typeof DocsCompFuncImport
      parentRoute: typeof rootRoute
    }
    '/docs/simz-concept': {
      id: '/docs/simz-concept'
      path: '/docs/simz-concept'
      fullPath: '/docs/simz-concept'
      preLoaderRoute: typeof DocsSimzConceptImport
      parentRoute: typeof rootRoute
    }
    '/project/$projectid/': {
      id: '/project/$projectid/'
      path: '/project/$projectid'
      fullPath: '/project/$projectid'
      preLoaderRoute: typeof ProjectProjectidIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginRoute
  '/tpp': typeof TppLazyRoute
  '/docs/code-arch': typeof DocsCodeArchRoute
  '/docs/comp-func': typeof DocsCompFuncRoute
  '/docs/simz-concept': typeof DocsSimzConceptRoute
  '/project/$projectid': typeof ProjectProjectidIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginRoute
  '/tpp': typeof TppLazyRoute
  '/docs/code-arch': typeof DocsCodeArchRoute
  '/docs/comp-func': typeof DocsCompFuncRoute
  '/docs/simz-concept': typeof DocsSimzConceptRoute
  '/project/$projectid': typeof ProjectProjectidIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/login': typeof LoginRoute
  '/tpp': typeof TppLazyRoute
  '/docs/code-arch': typeof DocsCodeArchRoute
  '/docs/comp-func': typeof DocsCompFuncRoute
  '/docs/simz-concept': typeof DocsSimzConceptRoute
  '/project/$projectid/': typeof ProjectProjectidIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/tpp'
    | '/docs/code-arch'
    | '/docs/comp-func'
    | '/docs/simz-concept'
    | '/project/$projectid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/tpp'
    | '/docs/code-arch'
    | '/docs/comp-func'
    | '/docs/simz-concept'
    | '/project/$projectid'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/tpp'
    | '/docs/code-arch'
    | '/docs/comp-func'
    | '/docs/simz-concept'
    | '/project/$projectid/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  LoginRoute: typeof LoginRoute
  TppLazyRoute: typeof TppLazyRoute
  DocsCodeArchRoute: typeof DocsCodeArchRoute
  DocsCompFuncRoute: typeof DocsCompFuncRoute
  DocsSimzConceptRoute: typeof DocsSimzConceptRoute
  ProjectProjectidIndexRoute: typeof ProjectProjectidIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  LoginRoute: LoginRoute,
  TppLazyRoute: TppLazyRoute,
  DocsCodeArchRoute: DocsCodeArchRoute,
  DocsCompFuncRoute: DocsCompFuncRoute,
  DocsSimzConceptRoute: DocsSimzConceptRoute,
  ProjectProjectidIndexRoute: ProjectProjectidIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/tpp",
        "/docs/code-arch",
        "/docs/comp-func",
        "/docs/simz-concept",
        "/project/$projectid/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/tpp": {
      "filePath": "tpp.lazy.tsx"
    },
    "/docs/code-arch": {
      "filePath": "docs/code-arch.tsx"
    },
    "/docs/comp-func": {
      "filePath": "docs/comp-func.tsx"
    },
    "/docs/simz-concept": {
      "filePath": "docs/simz-concept.tsx"
    },
    "/project/$projectid/": {
      "filePath": "project/$projectid/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
