/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProjectProjectidLayoutImport } from './routes/project/$projectid/_layout'
import { Route as ProjectProjectidLayoutIndexImport } from './routes/project/$projectid/_layout.index'
import { Route as ProjectProjectidLayoutAnaliticsImport } from './routes/project/$projectid/_layout.analitics'

// Create Virtual Routes

const TppLazyImport = createFileRoute('/tpp')()
const IndexLazyImport = createFileRoute('/')()
const ProjectProjectidImport = createFileRoute('/project/$projectid')()

// Create/Update Routes

const TppLazyRoute = TppLazyImport.update({
  id: '/tpp',
  path: '/tpp',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/tpp.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ProjectProjectidRoute = ProjectProjectidImport.update({
  id: '/project/$projectid',
  path: '/project/$projectid',
  getParentRoute: () => rootRoute,
} as any)

const ProjectProjectidLayoutRoute = ProjectProjectidLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => ProjectProjectidRoute,
} as any)

const ProjectProjectidLayoutIndexRoute =
  ProjectProjectidLayoutIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectProjectidLayoutRoute,
  } as any)

const ProjectProjectidLayoutAnaliticsRoute =
  ProjectProjectidLayoutAnaliticsImport.update({
    id: '/analitics',
    path: '/analitics',
    getParentRoute: () => ProjectProjectidLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/tpp': {
      id: '/tpp'
      path: '/tpp'
      fullPath: '/tpp'
      preLoaderRoute: typeof TppLazyImport
      parentRoute: typeof rootRoute
    }
    '/project/$projectid': {
      id: '/project/$projectid'
      path: '/project/$projectid'
      fullPath: '/project/$projectid'
      preLoaderRoute: typeof ProjectProjectidImport
      parentRoute: typeof rootRoute
    }
    '/project/$projectid/_layout': {
      id: '/project/$projectid/_layout'
      path: '/project/$projectid'
      fullPath: '/project/$projectid'
      preLoaderRoute: typeof ProjectProjectidLayoutImport
      parentRoute: typeof ProjectProjectidRoute
    }
    '/project/$projectid/_layout/analitics': {
      id: '/project/$projectid/_layout/analitics'
      path: '/analitics'
      fullPath: '/project/$projectid/analitics'
      preLoaderRoute: typeof ProjectProjectidLayoutAnaliticsImport
      parentRoute: typeof ProjectProjectidLayoutImport
    }
    '/project/$projectid/_layout/': {
      id: '/project/$projectid/_layout/'
      path: '/'
      fullPath: '/project/$projectid/'
      preLoaderRoute: typeof ProjectProjectidLayoutIndexImport
      parentRoute: typeof ProjectProjectidLayoutImport
    }
  }
}

// Create and export the route tree

interface ProjectProjectidLayoutRouteChildren {
  ProjectProjectidLayoutAnaliticsRoute: typeof ProjectProjectidLayoutAnaliticsRoute
  ProjectProjectidLayoutIndexRoute: typeof ProjectProjectidLayoutIndexRoute
}

const ProjectProjectidLayoutRouteChildren: ProjectProjectidLayoutRouteChildren =
  {
    ProjectProjectidLayoutAnaliticsRoute: ProjectProjectidLayoutAnaliticsRoute,
    ProjectProjectidLayoutIndexRoute: ProjectProjectidLayoutIndexRoute,
  }

const ProjectProjectidLayoutRouteWithChildren =
  ProjectProjectidLayoutRoute._addFileChildren(
    ProjectProjectidLayoutRouteChildren,
  )

interface ProjectProjectidRouteChildren {
  ProjectProjectidLayoutRoute: typeof ProjectProjectidLayoutRouteWithChildren
}

const ProjectProjectidRouteChildren: ProjectProjectidRouteChildren = {
  ProjectProjectidLayoutRoute: ProjectProjectidLayoutRouteWithChildren,
}

const ProjectProjectidRouteWithChildren =
  ProjectProjectidRoute._addFileChildren(ProjectProjectidRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/tpp': typeof TppLazyRoute
  '/project/$projectid': typeof ProjectProjectidLayoutRouteWithChildren
  '/project/$projectid/analitics': typeof ProjectProjectidLayoutAnaliticsRoute
  '/project/$projectid/': typeof ProjectProjectidLayoutIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/tpp': typeof TppLazyRoute
  '/project/$projectid': typeof ProjectProjectidLayoutIndexRoute
  '/project/$projectid/analitics': typeof ProjectProjectidLayoutAnaliticsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/tpp': typeof TppLazyRoute
  '/project/$projectid': typeof ProjectProjectidRouteWithChildren
  '/project/$projectid/_layout': typeof ProjectProjectidLayoutRouteWithChildren
  '/project/$projectid/_layout/analitics': typeof ProjectProjectidLayoutAnaliticsRoute
  '/project/$projectid/_layout/': typeof ProjectProjectidLayoutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tpp'
    | '/project/$projectid'
    | '/project/$projectid/analitics'
    | '/project/$projectid/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tpp' | '/project/$projectid' | '/project/$projectid/analitics'
  id:
    | '__root__'
    | '/'
    | '/tpp'
    | '/project/$projectid'
    | '/project/$projectid/_layout'
    | '/project/$projectid/_layout/analitics'
    | '/project/$projectid/_layout/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  TppLazyRoute: typeof TppLazyRoute
  ProjectProjectidRoute: typeof ProjectProjectidRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  TppLazyRoute: TppLazyRoute,
  ProjectProjectidRoute: ProjectProjectidRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/tpp",
        "/project/$projectid"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/tpp": {
      "filePath": "tpp.lazy.tsx"
    },
    "/project/$projectid": {
      "filePath": "project/$projectid",
      "children": [
        "/project/$projectid/_layout"
      ]
    },
    "/project/$projectid/_layout": {
      "filePath": "project/$projectid/_layout.tsx",
      "parent": "/project/$projectid",
      "children": [
        "/project/$projectid/_layout/analitics",
        "/project/$projectid/_layout/"
      ]
    },
    "/project/$projectid/_layout/analitics": {
      "filePath": "project/$projectid/_layout.analitics.tsx",
      "parent": "/project/$projectid/_layout"
    },
    "/project/$projectid/_layout/": {
      "filePath": "project/$projectid/_layout.index.tsx",
      "parent": "/project/$projectid/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
